#!/usr/bin/env bash
# This scripts uploads a local file to a cloud server using
# scp

num_command_line_arguments=$#
if test $num_command_line_arguments -eq 4
then
	PATH_TO_FILE=$1;
	IP=$2;
	USERNAME=$3;
	PATH_TO_SSH_KEY=$4
	#scp -i ~/.ssh/id_rsa  README.md  username@127.0.0.1:~/;
	scp -q -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r "$PATH_TO_FILE"  "$USERNAME"@"$IP":~/;
else 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi

