#!/usr/bin/env bash
# This Script Performs an apt update
# Installs nginx web server
# adds some content to the landing page
# Finally Starts the nginx service

sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo /etc/init.d/nginx start
