#!/usr/bin/env bash
# This Script Performs an apt update
# Installs nginx web server
# adds some content to the landing page
# Finally Starts the nginx service

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
/etc/init.d/nginx start
