#!/usr/bin/env bash
# This Script Performs an apt update
# Installs nginx web server
# adds some content to the landing page
# Adds a permanent redirect to a youtube url
# Finally Starts the nginx service

apt-get -y update
apt-get install -y nginx
echo "Hello World!                 " > /var/www/html/index.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
/etc/init.d/nginx restart
