#!/usr/bin/env bash
# This Script Performs an apt update
# Installs nginx web server
# adds some content to the landing page
# Adds a permanent redirect to a youtube url
# Finally Starts the nginx service

apt-get -y update
apt-get install -y nginx
echo "Hello World!                 " > /var/www/html/index.html
data="location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;} "
sed -i "/^\s*server_name _*/a $data" default
/etc/init.d/nginx start
