#!/usr/bin/env bash
# This Script Performs an apt update
# Installs nginx web server
# adds some content to the landing page
# Adds a permanent redirect to a youtube url
# Finally Starts the nginx service

apt-get -y update
apt-get install -y nginx
echo "Hello World!                 " > /var/www/html/index.html

data="location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;} "
sed -i "/^\s*server_name _*/a $data" /etc/nginx/sites-enabled/default

echo -e "Ceci n'est pas une page \n" > /var/www/html/404.html
snippet_data="error_page 404 /404.html;"
sed -i "/^\s*server_name _*/i $snippet_data" /etc/nginx/sites-enabled/default

/etc/init.d/nginx restart
