#!/usr/bin/env bash
# This script dumps the contents of the database
# tyrell_corp and backs it up to a tape archive
BACKUP_NAME='backup.sql'
if test $# -eq 1
then 
	mysqldump -h localhost -u root -p "$1" tyrell_corp > "$BACKUP_NAME"
	DATE=$(date +'%d-%m-%Y')
	tar cvfz  "$DATE.tar.gz" "$BACKUP_NAME"
else
	echo "Usage: $0 <mysql_root_password>"
fi
