#!/usr/bin/env bash
# configures nginx to run and listen to port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -s reload
