#!/usr/bin/env bash
# kills all processes that are spawned from bash and have the name "4-to_infinity_and_beyond"
process_name="4-to_infinity_and_beyond"
pids=$(pgrep -a bash | grep $process_name | cut --delimiter=" " -f 1)
#pids=$(ps -ef |grep "bash ./4-to_infinity_and_beyond" | grep -v "auto"| cut --delimiter=" " -f 6)
for ids in $pids; do
	if [ "$ids" -ne "$$" ]
	then
		kill "$ids"
	fi
done
