#!/usr/bin/env bash
# This script prints fizz on divisors of 3, buzz on divisors of 5
# and fizzbuzz where two conditions are met else prints the counter variable.
# prints from 1 to 100
counter=0
a=3
b=5
while [ $counter -lt 100 ];do
	((counter++))
	test3=$((counter % a))
	test5=$((counter % b))

	if [ $test3 -eq 0 ]
	then
		echo -n "Fizz"
	fi
	if [ $test5 -eq 0 ]
	then
		echo -n "Buzz"
	fi
	if [ $test3 -ne 0 ] && [ $test5 -ne 0 ]
	then
		echo -n "$counter"
	fi
	echo ""
done;
