#!/usr/bin/env bash
# This script prints #username #user id #Home directory path for the user Futher documents the details detailed within the /etc/shadow file
while read -r line;do
	user=$(echo "$line"|cut --delimiter=":" -f 1)
	gid=$(echo "$line"|cut --delimiter=":" -f 3)
	home=$(echo "$line"|cut --delimiter=":" -f 6)
	shell=$(echo "$line"|cut --delimiter=":" -f 7)
	hasher=$(echo "$line"|cut --delimiter=":" -f 2)

	string="The user $user is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode $hasher, more info about the user here: $user"
	echo "$string"
done < /etc/passwd
