#!/usr/bin/env bash
# This script prints "Best School" 9 times and "Hi" once
counter=0
while [ $counter -lt 10 ];do
	((counter++))
	if [ "$counter" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

done;
