#!/usr/bin/env bash
# This script prints "Best School" 10 times and "Hi" once
counter=0
while [ $counter -lt 11 ];do
	((counter++))
	if [ "$counter" -eq 10 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

done;
