#!/usr/bin/env bash
# This script uses case to print conditionally when counter is 4,9 and 17 respectively.
counter=0
while [ $counter -lt 20 ];do
	((counter++))
	case $counter in
		4) echo "$counter";echo "bad luck from China";;
		9) echo "$counter";echo "bad luck from Japan";;
		17) echo "$counter";echo "bad luck from Italy";;
		*) echo "$counter";;
	esac

done;
