#!/usr/bin/env bash
# This script counts up from 0:1 to 12:59
hour=0
minute=1
while [ $hour -lt 13 ];do
	echo "Hour: $hour"
	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
	minute=1
done;
