#!/usr/bin/env bash
# This script displays a directory listing without sequence numbers 
for file in $(find . -maxdepth 1 -type f -executable | cut --delimiter='-' -f 2| cut --delimiter="/" -f 2);do
	echo "$file"
done
