#!/usr/bin/env bash
# script modifies the contents of the hostfile and sets localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/^localhost\b.*$/localhost\t127.0.0.2/" ~/hosts.new 
sed -i "s/^facebook.com\b.*$/facebook.com\t8.8.8.8/"  ~/hosts.new
cp -f ~/hosts.new /etc/hosts
