#!/usr/bin/env bash
# prints all active ipv4 addresses on current machine
ifconfig | grep "inet\b"| grep -o "inet [[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}"| cut --delimiter=" " -f 2


